# Generated by Django 5.0.6 on 2024-06-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adquisiciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adquisicion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='adquisicion',
            name='nombre',
        ),
    ]
